import { useState, useEffect } from 'react';
import { Bell, ShieldAlert, AlertTriangle, Info, ArrowRight } from 'lucide-react';
import { Link } from 'react-router-dom';
import { fetchPriorityQueue } from '../services/mlApi';
import LoadingSpinner from '../components/shared/LoadingSpinner';

export default function Notifications() {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchPriorityQueue({ topN: 15 })
      .then(res => setAlerts(res?.items || []))
      .catch(err => console.error(err))
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-slate-900 dark:text-white">System Notifications & Risk Alerts</h1>
        <p className="text-sm text-slate-500 mt-1">
          Automated threshold breaches, high-risk flags, and data-quality warnings generated by the monitoring pipeline.
        </p>
      </div>

      {loading ? (
        <div className="py-16 flex justify-center"><LoadingSpinner /></div>
      ) : (
        <div className="space-y-3">
          {alerts.map((item, idx) => (
            <div
              key={item.project_id || idx}
              className="bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl p-4 flex items-start justify-between gap-4 hover:border-blue-400 transition-colors"
            >
              <div className="flex items-start gap-3">
                <div className="p-2 rounded-lg bg-rose-50 dark:bg-rose-950/40 text-rose-600 dark:text-rose-400 shrink-0 mt-0.5">
                  <ShieldAlert size={18} />
                </div>
                <div>
                  <div className="flex items-center gap-2">
                    <span className="font-mono font-bold text-sm text-slate-900 dark:text-white">{item.project_id}</span>
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-rose-100 text-rose-800 dark:bg-rose-900/40 dark:text-rose-300">
                      HIGH SCHEDULE RISK
                    </span>
                    <span className="text-xs text-slate-400">Score: {item.schedule_risk_score}</span>
                  </div>
                  <p className="text-xs text-slate-600 dark:text-slate-300 mt-1">
                    Project in {item.sector || 'general sector'} ({item.state || 'unspecified state'}) exceeded the operational threshold of 0.63.
                  </p>
                  <p className="text-[11px] text-slate-400 mt-1">Reported as of: {item.as_of}</p>
                </div>
              </div>

              <Link
                to={`/projects/${encodeURIComponent(item.project_id)}/risk?as_of=${item.as_of || ''}`}
                className="shrink-0 px-3 py-1.5 bg-slate-100 dark:bg-slate-700 hover:bg-blue-600 hover:text-white rounded-lg text-xs font-medium text-slate-700 dark:text-slate-200 inline-flex items-center gap-1 transition-colors"
              >
                Inspect <ArrowRight size={13} />
              </Link>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
